---
title: "Econ Forecasting ESN"
output: 
---

```{r}
library(tidyverse)
library(lubridate)
library(here)
library(matlab)
library(plotly)
```

## Load Data

```{r}
# --- Monthly data
Month_data = read_csv(paste0(here(), "/data/MonthlyIndicators_final.csv"), na = "");

# Select data, see Table 4.1
Mdata = Month_data %>%
  # NOTE: do not use BAA since it is missing in part of chosen sample
  select(
    Date, 
    AAA_logdf, MoneyBase_logdf, BusLoans_logdf, CPI_logdf, Curr_logdf,
    DSPIC_logdf, Housing_logdf, IPI_logdf, Loans_logdf, M2_logdf, Oil_logdf,
    PCE_logdf, PMI_logdf, PPI_logdf, TotalSL_logdf, Unemp_df
  ) %>%
  filter(
    Date >= as.Date("1976-01-01")
  )

# -- GDP data

GDP_data = read_csv(paste0(here(), "/data/GDP.csv")) 

GDP = GDP_data %>%
  filter(
    date >= as.Date("1976-01-01") 
  ) %>%
  filter(
    date <= as.Date("2012-06-01")
  )

```

## ESN Functions 

```{r}

ESN_states = function(y, A, C, h) {
  y = as.matrix(y)
  T. = size(y, 1)
  K = size(y, 2)
  
  X = matrix(0, nrow = T., ncol = size(A,1))
  X[1,] = y[1,] %*% C
  for (t in 2:T.) {
    X[t,] = h(X[t-1,] %*% A) + y[t,] %*% C
  }
  
  obj = list()
  obj$type = "ESN States"
  obj$states = X
  obj$y = y
  obj$A = A
  obj$C = C
  obj$h = h
  
  return(obj)
}

ESN_fit = function(y, X, lambda, intercept = TRUE) {
  y = as.matrix(y)
  X = as.matrix(X)
  
  # T. = size(y, 1)
  # K = size(y, 2)
  
  if (intercept) {
    X = cbind(rep(1, size(X, 1)), X)
  }
  
  M = size(X, 2)
  
  w = solve((t(X) %*% X + lambda*eye(M)), t(X)%*%y)
  
  yhat = X %*% w
  U = y - yhat
  
  obj = list()
  obj$type = "ESN Fit"
  obj$w = w
  obj$states = X
  obj$y = y
  obj$fitted = yhat
  obj$residuals = U
  obj$lambda = lambda
  
  return(obj)
}

```

```{r}

# GDP ESN

N_1 = 10
K_1 = 1
A_1 = matrix(rnorm(N_1*N_1), N_1, N_1)
A_1 = A_1 / max(abs(eigen(A_1)$values)) * 0.8
C_1 = matrix(runif(N_1*K_1), K_1, N_1)
C_1 = C_1 / norm(C_1, "2")

ESN_GDP_states = ESN_states(GDP$GDP, A_1, C_1, tanh)

# GDP_ahead = ESN_GDP_states$y[-1,]
# GDP_lag_states = ESN_GDP_states$states[1:199,]

# ESN_GDP_fit = ESN_fit(GDP_ahead, GDP_lag_states, 0)

# plot(ESN_GDP_fit$y, type = "l")
# lines(ESN_GDP_fit$fitted, col = "blue")

# Monthly Data ESN

Mx = Mdata[,-1] %>% as.matrix()
Mx = apply(Mx, 2, function(x)(x / std(x)))

N_2 = 50
K_2 = size(Mx, 2)

A_2 = matrix(rnorm(N_2*N_2), N_2, N_2)
A_2 = A_2 / max(abs(eigen(A_2)$values)) * 0.8
C_2 = matrix(runif(N_2*K_2), K_2, N_2)
C_2 = C_2 / norm(C_2, "2")

ESN_M_states = ESN_states(Mx, A_2, C_2, tanh)

```

## Fit

```{r}
# Create quarterly states

QM1_states = cbind(
  ESN_GDP_states$states[1:127],
  ESN_M_states$states[seq(3, 3*(127+1)-1, by=3),]
)

QM2_states = cbind(
  ESN_GDP_states$states[1:127],
  ESN_M_states$states[seq(4, 3*(127+1), by=3),]
)

QM3_states = cbind(
  ESN_GDP_states$states[1:127],
  ESN_M_states$states[seq(5, 3*(127+1), by=3),]
)

```

```{r}
# Fit 3 ESN models depending on month-of-quarter

GDP_ahead = GDP$GDP[2:128]

ESN_QM1_fit = ESN_fit(GDP_ahead, QM1_states, 0.1)
ESN_QM2_fit = ESN_fit(GDP_ahead, QM2_states, 0.1)
ESN_QM3_fit = ESN_fit(GDP_ahead, QM3_states, 0.1)

```

```{r}
# Plot fit
pd = data.frame(
  date = GDP$date[2:128],
  GDP_obs = GDP_ahead,
  GDP_ESN_QM1 = ESN_QM1_fit$fitted,
  GDP_ESN_QM2 = ESN_QM2_fit$fitted,
  GDP_ESN_QM3 = ESN_QM3_fit$fitted
)

plot_ly(pd, name = 'Fitted', type = 'scatter', mode = 'lines') %>%
  add_trace(x = ~date, y = ~GDP_obs, name="GDP", 
              line = list(color = 'black', width = 1, dash = 'dot')) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM1, name = "ESN QM1", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM2, name = "ESN QM2", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM3, name = "ESN QM3", 
              line = list(width = 1.2))
```

```{r}
# Plot residuals
pd = data.frame(
  date = GDP$date[2:128],
  zero = rep(0, length(2:128)),
  GDP_ESN_QM1 = ESN_QM1_fit$residuals,
  GDP_ESN_QM2 = ESN_QM2_fit$residuals,
  GDP_ESN_QM3 = ESN_QM3_fit$residuals
)

plot_ly(pd, name = 'Residuals', type = 'scatter', mode = 'lines') %>%
  add_trace(x = ~date, y = ~zero, name="", 
              line = list(color = 'black', width = 1, dash = 'dot')) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM1, name = "ESN QM1", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM2, name = "ESN QM2", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM3, name = "ESN QM3", 
              line = list(width = 1.2))
```
## Check forecasting

```{r}

GDP_forecast = GDP[133:146,]

# Create forecasting states
QM1_fore_states = cbind(
  rep(1, length(GDP_forecast)),
  ESN_GDP_states$states[132:145],
  ESN_M_states$states[seq(3*(132), 3*146-1, by=3),]
)

QM2_fore_states = cbind(
  rep(1, length(GDP_forecast)),
  ESN_GDP_states$states[132:145],
  ESN_M_states$states[seq(3*(132)+1, 3*146-1, by=3),]
)

QM3_fore_states = cbind(
  rep(1, length(GDP_forecast)),
  ESN_GDP_states$states[132:145],
  ESN_M_states$states[seq(3*(132)+2, 3*146-1, by=3),]
)

# Make 1-period ahead forecast

ESN_QM1_fore = QM1_fore_states %*% ESN_QM1_fit$w
ESN_QM2_fore = QM2_fore_states %*% ESN_QM2_fit$w
ESN_QM3_fore = QM3_fore_states %*% ESN_QM3_fit$w

```

```{r}
# Plot forecast
pd = data.frame(
  date        = GDP_forecast$date,
  GDP_obs     = GDP_forecast$GDP,
  GDP_ESN_QM1 = ESN_QM1_fore,
  GDP_ESN_QM2 = ESN_QM2_fore,
  GDP_ESN_QM3 = ESN_QM3_fore
)

plot_ly(pd, name = 'Forecast', type = 'scatter', mode = 'lines') %>%
  add_trace(x = ~date, y = ~GDP_obs, name="GDP", 
              line = list(color = 'black', width = 1, dash = 'dot')) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM1, name = "ESN QM1", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM2, name = "ESN QM2", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM3, name = "ESN QM3", 
              line = list(width = 1.2))

```
## Comparison: MIDAS model

```{r}
library(midasr)
```

```{r}
# Make explicit variables for MIDAS regression
GDP_lag = GDP$GDP[1:127]

AAA_month        = Mdata$AAA_logdf[3:(3*128-1)]
MoneyBase_month  = Mdata$MoneyBase_logdf[3:(3*128-1)]
BusLoans_month   = Mdata$BusLoans_logdf[3:(3*128-1)]
CPI_month        = Mdata$CPI_logdf[3:(3*128-1)]
Curr_month       = Mdata$Curr_logdf[3:(3*128-1)]
DSPIC_month      = Mdata$DSPIC_logdf[3:(3*128-1)]
Housing_month    = Mdata$Housing_logdf[3:(3*128-1)]
IPI_month        = Mdata$IPI_logdf[3:(3*128-1)]
Loans_month      = Mdata$Loans_logdf[3:(3*128-1)]
M2_month         = Mdata$M2_logdf[3:(3*128-1)]
Oil_month        = Mdata$Oil_logdf[3:(3*128-1)]
PCE_month        = Mdata$PCE_logdf[3:(3*128-1)]
PMI_month        = Mdata$PMI_logdf[3:(3*128-1)]
PPI_month        = Mdata$PPI_logdf[3:(3*128-1)]
TotalSL_month    = Mdata$TotalSL_logdf[3:(3*128-1)]
Unemp_month      = Mdata$Unemp_df[3:(3*128-1)]
```

```{r}
# MIDAS regression
GDP_midas = midas_r(GDP_ahead ~ 
                      mls(GDP_lag, 0:2, 1) +
                      mls(AAA_month, 0:2, 3, nealmon) +
                      mls(MoneyBase_month, 0:2, 3, nealmon) +
                      mls(BusLoans_month, 0:2, 3, nealmon) +
                      mls(CPI_month, 0:2, 3, nealmon) +
                      mls(Curr_month, 0:2, 3, nealmon) +
                      mls(DSPIC_month, 0:2, 3, nealmon) +
                      mls(Housing_month, 0:2, 3, nealmon) +
                      mls(IPI_month, 0:2, 3, nealmon) +
                      mls(Loans_month, 0:2, 3, nealmon) +
                      mls(M2_month, 0:2, 3, nealmon) +
                      mls(Oil_month, 0:2, 3, nealmon) +
                      mls(PCE_month, 0:2, 3, nealmon) +
                      mls(PMI_month, 0:2, 3, nealmon) +
                      mls(PPI_month, 0:2, 3, nealmon) +
                      mls(TotalSL_month, 0:2, 3, nealmon) +
                      mls(Unemp_month, 0:2, 3, nealmon),
                    start = list(
                      AAA_month = rep(0, 3),
                      MoneyBase_month = rep(0, 3),
                      BusLoans_month = rep(0, 3),
                      CPI_month = rep(0, 3),
                      Curr_month = rep(0, 3),
                      DSPIC_month = rep(0, 3),
                      Housing_month = rep(0, 3),
                      IPI_month = rep(0, 3),
                      Loans_month = rep(0, 3),
                      M2_month = rep(0, 3),
                      Oil_month = rep(0, 3),
                      PCE_month = rep(0, 3),
                      PMI_month = rep(0, 3),
                      PPI_month = rep(0, 3),
                      TotalSL_month = rep(0, 3),
                      Unemp_month = rep(0, 3)
                    ),
                    Ofunction = "optim", method = "Nelder-Mead")
```

```{r}
# Plot MIDAS fit & compare
pd = data.frame(
  date = GDP$date[(2+2):128],
  GDP_obs = GDP_ahead[(1+2):127],
  GDP_MIDAS = GDP_midas$fitted.values,
  GDP_ESN_QM3 = ESN_QM3_fit$fitted[(1+2):127]
)

plot_ly(pd, name = 'Fitted', type = 'scatter', mode = 'lines') %>%
  add_trace(x = ~date, y = ~GDP_obs, name="GDP", 
              line = list(color = 'black', width = 1, dash = 'dot')) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM3, name = "ESN QM3", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_MIDAS, name = "MIDAS", 
              line = list(width = 1.2))
```
```{r}
# Make explicit variables for MIDAS forecasting
GDP_lag_fore = GDP$GDP[130:145]

AAA_month_fore        = Mdata$AAA_logdf[(3*130):(3*146-1)]
MoneyBase_month_fore  = Mdata$MoneyBase_logdf[(3*130):(3*146-1)]
BusLoans_month_fore   = Mdata$BusLoans_logdf[(3*130):(3*146-1)]
CPI_month_fore        = Mdata$CPI_logdf[(3*130):(3*146-1)]
Curr_month_fore       = Mdata$Curr_logdf[(3*130):(3*146-1)]
DSPIC_month_fore      = Mdata$DSPIC_logdf[(3*130):(3*146-1)]
Housing_month_fore    = Mdata$Housing_logdf[(3*130):(3*146-1)]
IPI_month_fore        = Mdata$IPI_logdf[(3*130):(3*146-1)]
Loans_month_fore      = Mdata$Loans_logdf[(3*130):(3*146-1)]
M2_month_fore         = Mdata$M2_logdf[(3*130):(3*146-1)]
Oil_month_fore        = Mdata$Oil_logdf[(3*130):(3*146-1)]
PCE_month_fore        = Mdata$PCE_logdf[(3*130):(3*146-1)]
PMI_month_fore        = Mdata$PMI_logdf[(3*130):(3*146-1)]
PPI_month_fore        = Mdata$PPI_logdf[(3*130):(3*146-1)]
TotalSL_month_fore    = Mdata$TotalSL_logdf[(3*130):(3*146-1)]
Unemp_month_fore      = Mdata$Unemp_df[(3*130):(3*146-1)]

# Forecast
GDP_midas_fore = predict(GDP_midas,
                         list(
                           GDP_lag = GDP_lag_fore,
                           AAA_month = AAA_month_fore,
                           MoneyBase_month = MoneyBase_month_fore,
                           BusLoans_month = BusLoans_month_fore,
                           CPI_month = CPI_month_fore,
                           Curr_month = Curr_month_fore,
                           DSPIC_month = DSPIC_month_fore,
                           Housing_month = Housing_month_fore,
                           IPI_month = IPI_month_fore,
                           Loans_month = Loans_month_fore,
                           M2_month = M2_month_fore,
                           Oil_month = Oil_month_fore,
                           PCE_month = PCE_month_fore,
                           PMI_month = PMI_month_fore,
                           PPI_month = PPI_month_fore,
                           TotalSL_month = TotalSL_month_fore,
                           Unemp_month = Unemp_month_fore
                         ))
```

```{r}
# Plot MIDAS forecast & compare
pd = data.frame(
  date        = GDP_forecast$date,
  GDP_obs     = GDP_forecast$GDP,
  GDP_MIDAS   = GDP_midas_fore,
  GDP_ESN_QM1 = ESN_QM1_fore,
  GDP_ESN_QM2 = ESN_QM2_fore,
  GDP_ESN_QM3 = ESN_QM3_fore
)

plot_ly(pd, name = 'Forecast', type = 'scatter', mode = 'lines') %>%
  add_trace(x = ~date, y = ~GDP_obs, name="GDP", 
              line = list(color = 'black', width = 1, dash = 'dot')) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM1, name = "ESN QM1", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM2, name = "ESN QM2", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_ESN_QM3, name = "ESN QM3", 
              line = list(width = 1.2)) %>%
  add_trace(x = ~date, y = ~GDP_MIDAS, name = "MIDAS", 
              line = list(width = 1.2))
```

```{r}
# MSE compare

cat("MIDAS forecast MSE:   ", mean((GDP_midas_fore - GDP_forecast$GDP)^2), "\n")
cat("ESN QM1 forecast MSE: ", mean((ESN_QM1_fore - GDP_forecast$GDP)^2), "\n")
cat("ESN QM2 forecast MSE: ", mean((ESN_QM2_fore - GDP_forecast$GDP)^2), "\n")
cat("ESN QM3 forecast MSE: ", mean((ESN_QM3_fore - GDP_forecast$GDP)^2), "\n")


```

